// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbofmxnD8CaPPFbSbvFaUnay-QQvickJc',
    appId: '1:1076592432149:web:e3220ad0bde3f475976a1c',
    messagingSenderId: '1076592432149',
    projectId: 'testapp-5d271',
    authDomain: 'testapp-5d271.firebaseapp.com',
    storageBucket: 'testapp-5d271.appspot.com',
    measurementId: 'G-8V1EHDVKLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsEIt-yrZQDa5lMYPOCMksF_KBOUM6TYg',
    appId: '1:1076592432149:android:01b09a556b2b3264976a1c',
    messagingSenderId: '1076592432149',
    projectId: 'testapp-5d271',
    storageBucket: 'testapp-5d271.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC-0bmvdyswqvc-XoRJwHTUWBpzgXs1Hg',
    appId: '1:1076592432149:ios:863c493af2f74d77976a1c',
    messagingSenderId: '1076592432149',
    projectId: 'testapp-5d271',
    storageBucket: 'testapp-5d271.appspot.com',
    iosClientId: '1076592432149-8e2koj6127t5rl4a90o8cfno9liqehm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.devStackTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC-0bmvdyswqvc-XoRJwHTUWBpzgXs1Hg',
    appId: '1:1076592432149:ios:863c493af2f74d77976a1c',
    messagingSenderId: '1076592432149',
    projectId: 'testapp-5d271',
    storageBucket: 'testapp-5d271.appspot.com',
    iosClientId: '1076592432149-8e2koj6127t5rl4a90o8cfno9liqehm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.devStackTest',
  );
}
